channels:
- defaults
- conda-forge
dependencies:
- click=8.0.4
- ipykernel=6.25.0
- matplotlib=3.7.2
- numpy=1.26.0
- openpyxl=3.0.10
- pandas=2.0.3
- python=3.11.5
- python-dotenv=0.21.0
- pyyaml=6.0
- seaborn=0.12.2
- xlrd=2.0.1
name: int-pabellon
