channels:
- defaults
- conda-forge
dependencies:
- ipykernel=6.25.0
- matplotlib=3.7.2
- numpy=1.26.0
- openpyxl=3.0.10
- pandas=2.0.3
- python=3.11.5
- pyyaml=6.0
- seaborn=0.12.2
name: int-pabellon
